Bepro 1559 hard cancel bounties on management tab
taikai/webnetwork-events pull request #116
Opened 2023-04-13 22:16 UTC by MarcusviniciusLsantos

2023-04-14 18:35 UTC, vhcsilva requested changes

2023-04-14 19:24 UTC, MarcusviniciusLsantos commented on src/actions/get-bounty-canceled-event.ts
> +  const isHardCancel = ['open', 'ready'].includes(dbBounty?.state || '') && (dbBounty.fundingAmount === ('0' || undefined) || isFunded)
when it's a funding and it wasn't funded the draft time doesn't matter. so in this logic I will only have bounties that the draft time has already passed or were funded

2023-04-14 19:37 UTC, vhcsilva approved these changes

2023-04-19 08:33 UTC, moshmage approved these changes

2023-04-21 13:03 UTC, merged